// tag fragment <!-- -->
// varible fragment {{var_name}}

const template = {
    "container.xml": '<?xml version="1.0"?>\n<container\n version="1.0"\n xmlns="urn:oasis:names:tc:opendocument:xmlns:container"\n>\n<rootfiles>\n<rootfile\n full-path="OEBPS/standard.opf"\n media-type="application/oebps-package+xml"\n/>\n</rootfiles>\n</container>',
    "mimetype": "application/epub+zip",
    "page.xhtml": '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE html>\n<html\n xmlns="http://www.w3.org/1999/xhtml"\n xmlns:epub="http://www.idpf.org/2007/ops"\n xml:lang="ja"\n>\n<head>\n<meta charset="UTF-8" />\n<title>{{title}}</title>\n<link rel="stylesheet" type="text/css" href="../style/fixed-layout-jp.css"/>\n<meta name="viewport" content="width={{width}}, height={{height}}"/>\n</head>\n<body>\n<div class="main">\n<svg xmlns="http://www.w3.org/2000/svg" version="1.1"\n xmlns:xlink="http://www.w3.org/1999/xlink"\n width="100%" height="100%" viewBox="0 0 {{width}} {{height}}">\n<image width="100%" height="100%" preserveAspectRatio="{{position}}" xlink:href="{{image file src}}" />\n</svg>\n</div>\n</body>\n</html>',
    "fixed-layout-jp.css": '@charset "UTF-8";\n\nhtml,\nbody {\n    margin:    0;\n    padding:   0;\n    font-size: 0;\n}\nsvg {\n    margin:    0;\n    padding:   0;\n}',
    "standard.opf": '<?xml version="1.0" encoding="UTF-8"?>\n<package xmlns="http://www.idpf.org/2007/opf" version="3.0" xml:lang="ja" unique-identifier="unique-id" prefix="rendition: http://www.idpf.org/vocab/rendition/#         epub-bundle-tool: https://wing-kai.github.io/epub-manga-creator/         ebpaj: http://www.ebpaj.jp/         fixed-layout-jp: http://www.digital-comic.jp/">\n\n<metadata xmlns:dc="http://purl.org/dc/elements/1.1/">\n\n<!-- 作品名 -->\n<dc:title id="title">{{title}}</dc:title>\n<meta refines="#title" property="file-as"></meta>\n\n<!-- 著者名 -->\n<!-- creator-list -->\n\n<dc:subject>{{subject}}</dc:subject>\n\n<!-- 出版社名 -->\n<dc:publisher id="publisher">{{publisher}}</dc:publisher>\n<meta refines="#publisher" property="file-as"></meta>\n\n<!-- 言語 -->\n<dc:language>ja</dc:language>\n\n<!-- ファイルid -->\n<dc:identifier id="unique-id">urn:uuid:{{uuid}}</dc:identifier>\n\n<!-- 更新日 -->\n<meta property="dcterms:modified">{{createTime}}</meta>\n\n<!-- Fixed-Layout Documents指定 -->\n<meta property="rendition:layout">pre-paginated</meta>\n<meta property="rendition:spread">landscape</meta>\n\n<!-- etc. -->\n<meta property="ebpaj:guide-version">1.1</meta>\n<meta name="SpineColor" content="#FFFFFF"></meta>\n<meta name="cover" content="cover"></meta>\n\n</metadata>\n\n<manifest>\n\n<!-- navigation -->\n<item media-type="application/xhtml+xml" id="toc" href="navigation-documents.xhtml" properties="nav"></item>\n\n<!-- style -->\n<item media-type="text/css" id="fixed-layout-jp" href="style/fixed-layout-jp.css"></item>\n\n<!-- image -->\n<!-- item-image -->\n\n<!-- text -->\n<item id="p-cover" href="text/p_cover.xhtml" media-type="application/xhtml+xml" properties="svg" fallback="cover"></item>\n<!-- item-xhtml -->\n\n</manifest>\n\n<spine{{direction}}>\n\n<itemref linear="yes" idref="p-cover" properties="rendition:page-spread-center"></itemref>\n<!-- itemref-xhtml -->\n\n</spine>\n\n</package>',
    "navigation-documents.xhtml": '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="ja">\n<head>\n<meta charset="UTF-8"></meta>\n<title>Navigation</title>\n</head>\n<body>\n<nav epub:type="toc" id="toc">\n<h1>Navigation</h1>\n<ol>\n<!-- navigation-list -->\n</ol>\n</nav>\n<nav epub:type="landmarks">\n<ol>\n<li><a epub:type="bodymatter" href="text/p_cover.xhtml">Start of Content</a></li>\n</ol>\n</nav>\n</body>\n</html>',
}

export default template