// tag fragment <!-- -->
// varible fragment {{var_name}}

const template = {
    "page.css": "html,body,div{width:100%;height:100%;padding:0;margin:0;}div.img{display:block;background-repeat:no-repeat;background-position:center;width:100%;height:100%;}div.img.stretch{background-size:100%100%;}div.img.fill{background-size:cover;}div.img.fit{background-size:contain;}div.img.center{}div.img.bg-white{background-color:#fff}div.img.bg-black{background-color:#000}",
    "container.xml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><container xmlns=\"urn:oasis:names:tc:opendocument:xmlns:container\" version=\"1.0\"><rootfiles><rootfile full-path=\"OPS/package.opf\" media-type=\"application/oebps-package+xml\"/></rootfiles></container>",
    "mimetype": "application/epub+zip",
    "toc.xhtml": '<?xml version="1.0" encoding="UTF-8"?><html><head><title>{{title}}</title></head><body epub:type="frontmatter"><header><h1>{{ncxTitle}}</h1></header><nav epub:type="toc" id="toc"><ol><!-- toc --></ol></nav><nav epub:type="page-list"><ol><!-- page list --></ol></nav></body></html>',
    "toc.ncx": '<?xml version="1.0" encoding="utf-8" standalone="no"?><ncx:ncx xmlns:ncx="http://www.daisy.org/z3986/2005/ncx/" version="2005-1"><ncx:head><ncx:meta name="dtb:uid" content="urn:uuid:{{uuid}}"/><ncx:meta name="dtb:depth" content="-1"/><ncx:meta name="dtb:totalPageCount" content="0"/><ncx:meta name="dtb:maxPageNumber" content="0"/></ncx:head><ncx:docTitle><ncx:text>{{title}}</ncx:text></ncx:docTitle><ncx:docAuthor><ncx:text>{{creator}}</ncx:text></ncx:docAuthor><ncx:navMap><!-- nav map --></ncx:navMap></ncx:ncx>',
    "page.xhtml": '<?xml version="1.0" encoding="utf-8"?><html xml:lang="{{language}}" xmlns="http://www.w3.org/1999/xhtml" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:epub="http://www.idpf.org/2007/ops"><head><title>{{title}}</title><meta name="viewport" content="{{viewport}}"/><link rel="stylesheet" href="../css/page.css" type="text/css" /></head><body epub:type="bodymatter"><div style="background-image: url(\'{{image file src}}\')" class="img {{position}} {{backgroundColor}}"></div></body></html>',
    "package.opf": '<?xml version="1.0" encoding="UTF-8"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" xml:lang="{{language}}" prefix="rendition: http://www.idpf.org/vocab/rendition/#" unique-identifier="ootuya-id"><metadata xmlns:opf="http://www.idpf.org/2007/opf" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/"><dc:identifier id="ootuya-id">urn:uuid:{{uuid}}</dc:identifier><dc:title>{{title}}</dc:title><dc:language>{{language}}</dc:language><dc:subject>{{subject}}</dc:subject><dc:creator>{{creator}}</dc:creator><dc:publisher></dc:publisher><dc:rights></dc:rights><meta property="dcterms:modified">{{createTime}}</meta><meta property="rendition:layout">pre-paginated</meta><meta property="rendition:orientation">portrait</meta><meta property="rendition:spread">landscape</meta></metadata><manifest><item id="page-style" href="css/page.css" media-type="text/css"/><!-- image item --><item id="toc" properties="nav" href="xhtml/toc.xhtml" media-type="application/xhtml+xml"/><!-- page.xhtml item --><item id="ncxtoc" href="xhtml/toc.ncx" media-type="application/x-dtbncx+xml"/></manifest><spine toc="ncxtoc" page-progression-direction="rtl"><!-- image item ref --></spine></package>'
}

export default template